<template>
  <div id="app" class="clear-fix site-wrapper">
    <Header :current="'home'" :data="this.header"></Header>
    <main id="page" class="container">
      <article id="sections" class="sections">
        <Terms :data="this.terms"></Terms>
      </article>
    </main>
    <Footer :data="this.footer"></Footer>
  </div>
</template>

<script>
import Header from "@/components/Header";
import Terms from "@/components/Terms";
import Footer from "@/components/Footer";

export default {
  name: 'App',
  data() {
    return {
      header: {
        logo: '/assets/logo.png',
      },
      terms: {
        title: 'Monkeybrix Terms & Conditions',
        lists: [
          {
            subject: "Terms of Use",
            context:
                "These Terms of Use (“Terms”) apply to your purchase, sale and display of Monkeybrix non-fungible tokens (“MonkeybrixNFTs”). These Terms are entered into between you and Monkeybrix. (the “Company,” “we,” or “us”). You must agree to these Terms before using this website and before you purchase a MonkeybrixNFT for the first time or activate a previously purchased MonkeybrixNFT. By agreeing to these Terms, you hereby certify that you are at least 18 years of age. Monkeybrix reserves the right to change or modify these Terms at any time and in its sole discretion." +
                "\nMonkeybrixNFTs are stored on and accessible through the Ethereum blockchain. As such, the Company does not maintain the MonkeybrixNFTs and has no control over the transfer, storage, ownership or maintenance of the MonkeybrixNFTs. This website is only an interface allowing participants to exchange digital collectibles. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval."
          }, {
            subject: "Terms of Sale",
            context:
                "By placing an order on the Monkeybrix website, you agree that you are submitting a binding offer to purchase an MonkeybrixNFT. In addition, when you buy a MonkeybrixNFT on this Site, you agree to pay all applicable fees associated with the transaction. No refunds are permitted. If you are the initial purchaser of a MonkeybrixNFT, then all amounts due are to be paid to Monkeybrix. If you are not the initial purchaser of a MonkeybrixNFT, then amounts may be paid to the-then holder of the MonkeybrixNFT." +
                "\nThere will be a limited number of MonkeybrixNFT for initial sale. All sales are final and we do not guarantee that all interested buyers will be able to purchase a MonkeybrixNFT before they are sold out. We disclaim all liability in connection with the purchase of any MonkeybrixNFTs. It is your responsibility to ensure that your purchase of any MonkeybrixNFTs has been completed. We reserve the right to terminate or end the initial sale of MonkeybrixNFTs at any time." +
                "\nWhen you link your cryptocurrency wallet, you understand and agree that you are solely responsible for maintaining the security of your wallet and your control over any wallet-related authentication credentials, private or public cryptocurrency keys, non-fungible tokens or cryptocurrencies that are stored in or are accessible through your wallet."
          }, {
            subject: "Intellectual Property",
            context: "Monkeybrix and all content and other materials contained therein, including, without limitation, logos, text, graphics, artwork, pictures, video files, films, animation, shows, merchandise, sound files, information, software, data, other files, and the selection and arrangement thereof (collectively, “Monkeybrix Content”) are the Company’s property or its affiliates, licensors, or as applicable. The name Monkeybrix, the Monkeybrix logo, and any slogan, name, logo or mark associated with any Monkeybrix product or service (including those that may appear on Monkeybrix or elsewhere) (collectively, “Monkeybrix Marks”) are trademarks owned by the Company or its affiliates, and may not be copied, imitated or used, in whole or in part, without the Company’s express prior written permission."
          }, {
            subject: "Ownership",
            context: "MonkeybrixNFTs are unique digital creations based upon content that is owned exclusively by the Company. When you purchase a MonkeybrixNFT you own only the NFT and not the associated art or other intellectual property. You agree that purchasing a MonkeybrixNFT does not include the purchase of any copyright in the MonkeybrixNFT or its content and you understand and agree that the Company may sell, license, modify, display, publish and create derivative works (Derivative works include but is not limited to: videos, films, animations, shows, books, merchandise, apparel, toys, accessories, digital media, etc...) based upon your MonkeybrixNFT or its content."
          }, {
            subject: "General Use",
            context: "Subject to your full and continued compliance with these Terms, the Company grants you a limited worldwide, non-exclusive, non-transferable, royalty-free license to use, copy, and display your MonkeybrixNFT and MonkeybrixNFT image (“MonkeybrixNFT Art”) solely for the following purposes: (a) for your own personal, non-commercial use; (b) as part of a marketplace that permits the purchase and sale of your MonkeybrixNFT, provided that the marketplace cryptographically verifies each MonkeybrixNFT owner’s rights to display the MonkeybrixNFT; or (c) as part of a third-party website or application that permits the inclusion, involvement, or participation of your MonkeybrixNFT, provided that the website/application cryptographically verifies each MonkeybrixNFT owner’s rights to display the MonkeybrixNFT."
          }, {
            subject: "Disclaimers",
            context: "MONKEYBRIX, MONKEYBRIX WEBSITE AND ANY MONKEYBRIX CONTENT CONTAINED THEREIN, AND ANY AND ALL MONKEYBRIXNFTs PROVIDED BY THE COMPANY OR LISTED THEREIN ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. THE COMPANY, AND ITS RESPECTIVE PAST, PRESENT AND FUTURE EMPLOYEES, OFFICERS, DIRECTORS, CONTRACTORS, CONSULTANTS, EQUITY HOLDERS, SUPPLIERS, VENDORS, SERVICE PROVIDERS, PARENT COMPANIES, SUBSIDIARIES, AFFILIATES, AGENTS, REPRESENTATIVES, PREDECESSORS, SUCCESSORS AND ASSIGNS MAKE NO WARRANTY THAT MONKEYBRIX WILL (1) MEET YOUR REQUIREMENTS; (2) BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (3) BE ACCURATE, RELIABLE, COMPLETE, OR SAFE."
          }, {
            subject: "Risks",
            context: "You agree and understand that you are solely responsible for determining the nature, potential value, suitability, and appropriateness of these risks for yourself. You agree and understand that you access and use this Site at your own risk. You agree and understand that we will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using Monkeybrix, however caused."
          }, {
            subject: "Limitations of Liability for Gas, Failed Transactions, Smart Contract Bugs",
            context: "You agree to hold The Company harmless for any losses you may incur as a consequence of minting your NFT. These potential losses include any gas fees for failed transactions, any excessive gas fees charged due to website or smart contract bugs, and any loss of your NFT due to website or smart contract bugs."
          }, {
            subject: "No Guarantees or Future Promises",
            context: "You agree that your purchase of a MonkeybrixNFT from our initial project is all you receive with your initial purchase. Any future potential airdrops, memberships, rewards, promotions, shows, activities or other benefits are ancillary to this purchase and not to be taken into consideration with your initial purchase. You agree that you are not relying on any future commitments by Monkeybrix in using this site and participating in our NFT launch."
          }, {
            subject: "MonkeybrixNFTs Are Not Intended as Investments",
            context: "MonkeybrixNFTs are Non-Fungible Token for you to collect. They are not meant as investment vehicles. We make absolutely no promise or guarantee that these NFTs will be worth anything. You understand that they have no inherent monetary value, and they should be treated as nothing more than a collectible."
          }, {
            subject: "Taxes",
            context: "You are entirely responsible for any tax liability which may arise from minting or reselling your MonkeybrixNFT. We are not responsible for determining the withholding, sales, use, value added, transfer or other taxes, together with any interest and penalties imposed with respect thereto (“Taxes”), that may apply to transactions on this Site."
          }, {
            subject: "Indemnification",
            context: "To the fullest extent permitted by applicable law, you agree to indemnify, defend and hold harmless the Company, and our respective past, present and future employees, officers, directors, contractors, consultants, equity holders, suppliers, vendors, service providers, parent companies, subsidiaries, affiliates, agents, representatives, predecessors, successors and assigns (individually and collectively, the “Monkeybrix”), from and against all actual or alleged third party claims."
          }, {
            subject: "Third Party Sites",
            context: "Monkeybrix website may permit you to link to other websites, services or resources on the Internet, which are provided solely as a convenience to you. You access these third-party websites, services or resources at your own risk."
          }, {
            subject: "Children",
            context: "The Monkeybrix project is not targeted towards children. You agree that you are over the age of 18."
          }
        ]
      },
      footer: {
        link: {
          twitter: "https://twitter.com/monkeybrix",
          discord: "https://discord.gg/PytJDTJEKp",
          instagram: "https://www.instagram.com/monkeybrix",
        },
        logo: "/assets/logo.png",
        copyright: "All Rights Reserved, MONKEYBRIX 2021",
        terms: {
          link: "/terms-and-conditions"
        },
      }
    }
  },
  components: {
    Header,
    Terms,
    Footer,
  }
}
</script>

<style>

</style>
